# Generated by Django 5.2.7 on 2025-10-20 07:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='T001Estudiantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=50, unique=True, verbose_name='T001_identificación')),
                ('tipo_documento', models.CharField(help_text='CC, TI, RC, etc.', max_length=10, verbose_name='T001_tipo_documento')),
                ('primer_nombre', models.CharField(max_length=50, verbose_name='T001_primer_nombre')),
                ('segundo_nombre', models.CharField(blank=True, max_length=50, null=True, verbose_name='T001_segundo_nombre')),
                ('primer_apellido', models.CharField(max_length=50, verbose_name='T001_primer_apellido')),
                ('segundo_apellido', models.CharField(blank=True, max_length=50, null=True, verbose_name='T001_segundo_apellido')),
                ('foto', models.CharField(blank=True, max_length=255, null=True, verbose_name='T001_foto')),
                ('genero', models.CharField(help_text='M / F', max_length=5, verbose_name='T001_género')),
                ('fecha_nacimiento', models.DateField(verbose_name='T001_fecha_nacimiento')),
                ('direccion', models.CharField(max_length=200, verbose_name='T001_dirección')),
                ('telefono', models.CharField(max_length=15, verbose_name='T001_teléfono')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='T001_correo_electrónico')),
                ('grado', models.CharField(max_length=20, verbose_name='T001_grado')),
                ('grupo', models.CharField(max_length=10, verbose_name='T001_grupo')),
                ('jornada', models.CharField(help_text='Mañana, Tarde o Nocturna', max_length=20, verbose_name='T001_jornada')),
                ('año_ingreso', models.IntegerField(verbose_name='T001_año_ingreso')),
                ('estado', models.BooleanField(default=True, verbose_name='T001_estado')),
                ('creditos', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='T001_créditos')),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now, verbose_name='T001_creado_en')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'db_table': 'T001Estudiantes',
            },
        ),
        migrations.CreateModel(
            name='T003MenuDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True, verbose_name='T003_fecha')),
                ('descripcion', models.TextField(verbose_name='T003_descripción')),
                ('plato_principal', models.CharField(max_length=100, verbose_name='T003_plato_principal')),
                ('acompanamiento', models.CharField(max_length=100, verbose_name='T003_acompañamiento')),
                ('bebida', models.CharField(max_length=100, verbose_name='T003_bebida')),
                ('postre', models.CharField(max_length=100, verbose_name='T003_postre')),
                ('calorias_total', models.IntegerField(verbose_name='T003_calorías_total')),
            ],
            options={
                'verbose_name': 'Menú del Día',
                'verbose_name_plural': 'Menús del Día',
                'db_table': 'T003MenuDia',
            },
        ),
        migrations.CreateModel(
            name='T006Parametros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='T006_nombre')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='T006_valor')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='T006_descripción')),
            ],
            options={
                'verbose_name': 'Parámetro',
                'verbose_name_plural': 'Parámetros',
                'db_table': 'T006Parametros',
            },
        ),
        migrations.CreateModel(
            name='T002Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(help_text='1=Enero, 2=Febrero, etc.', verbose_name='T002_mes')),
                ('anio', models.IntegerField(verbose_name='T002_año')),
                ('valor_pagado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='T002_valor_pagado')),
                ('valor_mensualidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='T002_valor_mensualidad')),
                ('fecha_pago', models.DateField(verbose_name='T002_fecha_pago')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='T002_observación')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlmuerzoCheck.t001estudiantes', verbose_name='T002_estudiante')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'T002Pagos',
            },
        ),
        migrations.CreateModel(
            name='T004Consumos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='T004_fecha')),
                ('hora', models.TimeField(default=django.utils.timezone.now, verbose_name='T004_hora')),
                ('repetido', models.BooleanField(default=False, verbose_name='T004_repetido')),
                ('reclamado', models.BooleanField(default=False, verbose_name='T004_reclamado')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlmuerzoCheck.t001estudiantes', verbose_name='T004_estudiante')),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AlmuerzoCheck.t003menudia', verbose_name='T004_menú')),
            ],
            options={
                'verbose_name': 'Consumo',
                'verbose_name_plural': 'Consumos',
                'db_table': 'T004Consumos',
            },
        ),
        migrations.CreateModel(
            name='T005Sugerencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(verbose_name='T005_comentario')),
                ('calificacion', models.IntegerField(help_text='Puntaje de 1 a 5', verbose_name='T005_calificación')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='T005_fecha')),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AlmuerzoCheck.t001estudiantes', verbose_name='T005_estudiante')),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AlmuerzoCheck.t003menudia', verbose_name='T005_menú')),
            ],
            options={
                'verbose_name': 'Sugerencia',
                'verbose_name_plural': 'Sugerencias',
                'db_table': 'T005Sugerencias',
            },
        ),
        migrations.CreateModel(
            name='T007UsuariosSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='T007_username')),
                ('password', models.CharField(max_length=200, verbose_name='T007_password')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('empleado', 'Empleado'), ('estudiante', 'Estudiante')], default='estudiante', help_text='admin | empleado | estudiante', max_length=20, verbose_name='T007_rol')),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now, verbose_name='T007_creado_en')),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AlmuerzoCheck.t001estudiantes', verbose_name='T007_estudiante')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario del Sistema',
                'verbose_name_plural': 'Usuarios del Sistema',
                'db_table': 'T007UsuariosSistema',
            },
        ),
    ]
