# Generated by Django 5.2.7 on 2025-10-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlmuerzoCheck', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='t007usuariossistema',
            name='correo_electronico',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='T007_correo_electrónico'),
        ),
    ]
