# Generated by Django 5.2.7 on 2025-10-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlmuerzoCheck', '0002_t007usuariossistema_correo_electronico'),
    ]

    operations = [
        migrations.AddField(
            model_name='t007usuariossistema',
            name='codigo_expira',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t007usuariossistema',
            name='codigo_recuperacion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
