# Generated by Django 5.2.7 on 2025-10-21 13:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlmuerzoCheck', '0003_t007usuariossistema_codigo_expira_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t007usuariossistema',
            name='codigo_expira',
        ),
        migrations.RemoveField(
            model_name='t007usuariossistema',
            name='codigo_recuperacion',
        ),
        migrations.CreateModel(
            name='T008Acudientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='T008_nombre')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='T008_telefono')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='T008_correo')),
                ('parentesco', models.CharField(blank=True, max_length=50, null=True, verbose_name='T008_parentesco')),
                ('direccion', models.CharField(blank=True, max_length=200, null=True, verbose_name='T008_direccion')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='T008_fecha_nacimiento')),
                ('ocupacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='T008_ocupacion')),
                ('estado', models.BooleanField(default=True, verbose_name='T008_estado')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='T008_observacion')),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now, verbose_name='T008_creado_en')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acudientes', to='AlmuerzoCheck.t001estudiantes', verbose_name='T008_estudiante')),
            ],
            options={
                'verbose_name': 'Acudiente',
                'verbose_name_plural': 'Acudientes',
                'db_table': 'T008Acudientes',
            },
        ),
    ]
