# Generated by Django 5.2.7 on 2025-10-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlmuerzoCheck', '0004_remove_t007usuariossistema_codigo_expira_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='t007usuariossistema',
            name='codigo_expira',
            field=models.DateTimeField(blank=True, null=True, verbose_name='T007_codigo_expira'),
        ),
        migrations.AddField(
            model_name='t007usuariossistema',
            name='codigo_recuperacion',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='T007_codigo_recuperacion'),
        ),
    ]
