# Generated by Django 5.2.7 on 2025-10-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlmuerzoCheck', '0005_t007usuariossistema_codigo_expira_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='t001estudiantes',
            name='fotoId',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_estudiantes/', verbose_name='T001_fotoId'),
        ),
    ]
