# Generated by Django 5.2.7 on 2025-10-30 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlmuerzoCheck', '0006_t001estudiantes_fotoid'),
    ]

    operations = [
        migrations.AddField(
            model_name='t001estudiantes',
            name='encoding_face',
            field=models.BinaryField(blank=True, null=True, verbose_name='T001_encoding_face'),
        ),
    ]
