# Generated by Django 5.2.7 on 2025-10-30 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AlmuerzoCheck', '0007_t001estudiantes_encoding_face'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t001estudiantes',
            name='encoding_face',
        ),
    ]
