# Generated by Django 5.2.7 on 2025-10-31 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AlmuerzoCheck', '0008_remove_t001estudiantes_encoding_face'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t004consumos',
            name='reclamado',
        ),
        migrations.RemoveField(
            model_name='t004consumos',
            name='repetido',
        ),
    ]
