# Generated by Django 5.2.7 on 2025-10-31 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlmuerzoCheck', '0009_remove_t004consumos_reclamado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='t003menudia',
            name='fotoId',
            field=models.ImageField(blank=True, null=True, upload_to='menu/', verbose_name='T003_fotoId'),
        ),
        migrations.AddField(
            model_name='t005sugerencias',
            name='fotoId',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_sugerencias/', verbose_name='T005_fotoId'),
        ),
    ]
