# Generated by Django 5.2.7 on 2025-11-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlmuerzoCheck', '0010_t003menudia_fotoid_t005sugerencias_fotoid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t001estudiantes',
            name='creditos',
            field=models.IntegerField(default=0, verbose_name='T001_créditos'),
        ),
    ]
