# Generated by Django 5.2.7 on 2025-11-06 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AlmuerzoCheck', '0011_alter_t001estudiantes_creditos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t002pagos',
            name='observacion',
        ),
        migrations.RemoveField(
            model_name='t002pagos',
            name='valor_pagado',
        ),
    ]
